server:
  port:8080
spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/crud191008?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:com.dossen.demo.mapper/*Mapper.xml
  type-aliases-package: com.dossen.demo.domain
#logging:
#  level:
#  file: F:/logging-boot.log